### ISSUE TITLE
About us wrapping

### ISSUE THREAD

**Issue by iPhatty** [fac-13/JIKTDEVS#47]
Just a personal preference, how about making the .about__content class have a smaller max-width. This would allow the text to be more compact and have less empty space between the lines. I had a little play, how about max-width of around 63%?

**Comment by jenath** [comment]
Thank you Phat. We changed the max-width to 63%, we prefer your preference. Please confirm issue has been resolved.

**Comment by iPhatty** [comment]
Nice one! 👍
